MyApp/MyApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('',include('home.urls')),
    path('accounts/',include('allauth.urls')),
    path('wallet/',include('wallet.urls')),
    path('play/',include('game.urls')),
]
handler404 = 'home.views.view_404'
handler403 = 'home.views.view_403'
handler500 = 'home.views.view_500'
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyApp/game/urls.py
from . import views
from django.urls import path

app_name = 'game'
urlpatterns = [
    path('start/',views.start_game, name='start'),
    path('round/', views.play_round, name='play_round'),
]

MyApp/home/urls.py
from . import views
from django.urls import path
app_name = 'home'
urlpatterns = [
    path('',views.dashboard, name='home'),
]

MyApp/user/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .decorators import redirect_if_authenticated

app_name = 'user'
urlpatterns = [
    path('login/',redirect_if_authenticated(views.loginViews), name='login'),
    path('register/',redirect_if_authenticated(views.signup), name='register'),
    path('validation/username/',lambda request: views.check_unique(request, 'username'), name='validate_username'),
    path('validation/email/',lambda request: views.check_unique(request, 'email'), name='validate_email'),
    path('validation/first_name/',lambda request: views.check_unique(request, 'first_name'), name='validate_first_name'),
    path('validation/last_name/',lambda request: views.check_unique(request, 'last_name'), name='validate_last_name'),
    path('signout/',views.logoutViews, name='signout'),
    path('profile/',views.viewsProfile, name='profile'),
    path('updateProfile/', views.updateProfile, name='updateProfile'),
    
    #change password
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='user/changePassword.html',success_url = reverse_lazy("user:password_change_done")), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='user/passwordChangeDone.html'), name='password_change_done'),
    
    #using email to reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html',
        success_url=reverse_lazy('user:password_reset_done')
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'
    ), name='password_reset_complete'),
]

MyApp/wallet/urls.py
from django.urls import path
from . import views

app_name = 'wallet'

urlpatterns = [
    path('buy/',views.payment, name='buy_point'),
    path('history/', views.payment_history, name='payment_history'),
]

MyApp/home/models.py
from django.db import models

# Create your models here.

MyApp/home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='user:login') #use decorator
def dashboard(request):
    return render(request,'home/dashboard.html')

def view_404(requests, exception):
    return render(requests, 'home/404.html', status=404)

def view_403(requests, exception):
    return render(requests, 'home/403.html', status=403)

def view_500(requests):
    return render(requests, 'home/500.html', status=500)

def csrf_failure(request, reason=""):
    return render(request, 'home/403.html', status=403)

MyApp/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% block css %}
    {% endblock css %}
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% comment %} <link href="{% static 'home/css/animate.css' %}" rel="stylesheet" /> {% endcomment %}
    <link href="{% static 'home/css/main.css' %}" rel="stylesheet" />
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" sizes="256x256" href="{% static 'favicon.ico' %}"/>
  </head>
  <!-- /head -->

  <body>
    <header id="header">
      <!-- header -->
      <div class="header_top">
        <!-- header_top -->
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <div class="contactinfo">
                <ul class="nav nav-pills">
                  <li>
                    <a href=""><i class="fa fa-phone"></i> +84 967 039 774</a>
                  </li>
                  <li>
                    <a href=""><i class="fa fa-envelope"></i> nguyenduyphuc162003@gmail.com</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="social-icons pull-right">
                <ul class="nav navbar-nav">
                  <li>
                    <a href=""><i class="fa fa-brands fa-facebook-f"></i></a>
                  </li>
                  <li>
                    <a href=""><i class="fa fa-brands fa-google"></i></a>
                  </li>
                  <li>
                    <a href=""><i class="fa fa-solid fa-message"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /header_top -->

      <div class="header-middle">
        <!-- header-middle -->
        <div class="container">
          <div class="row">
            <div class="col-sm-4 ">
              <div class="logo pull-left">
                <a href="{% url 'home:home' %}"><img src="{% static 'home/img/logo.png' %}" alt=""/></a>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="shop-menu pull-right">
                <ul class="nav navbar-nav">
                  <li>
                    <a href="{% url 'user:profile' %}"><i class="fa fa-user"></i> {{user.username}}</a>
                  </li>
                  <li>
                    <a href="{% url 'wallet:buy_point' %}"><i class="fa fa-coins"></i><span id="profile-point">{{profile.point}}</span></a>
                  </li>
                  <li>
                    <a href="{% url 'wallet:payment_history' %}"><i class="fa fa-wallet"></i> Wallet</a>
                  </li>
                  <li>
                    <a href="{% url 'user:signout' %}"><i class="fa fa-lock"></i> Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /header-middle -->
    </header>
    <main>
      <div class="container">
        {% block main-content %}
        {% endblock main-content %}
      </div>  
    </main>

    <footer id="footer">
      <!-- Footer -->
      <div class="footer-widget">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Service</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li>
                    <a href="">Online Help</a>
                  </li>
                  <li>
                    <a href="">Contact Us</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Support</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li>
                    <a href="">Game instructions</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Policies</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li>
                    <a href="">Terms of Use</a>
                  </li>
                  <li>
                    <a href="">Privecy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>About Game</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li>
                    <a href="">Copyright</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1">
              <div class="single-widget">
                <h2>About Game</h2>
                <p>Copyright © 2024 Number Guessing Game. All rights reserved. Designed by Nguyen Duy Phuc</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- /Footer -->
    {% block js %}
    {% endblock js %}
    <script src="{% static 'home/js/jquery.js' %}"></script>
    <script src="{% static 'home/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/main.js' %}"></script>
  </body>
</html>

MyApp/templates/home/dashboard.html
{% extends 'home/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'home/css/dashboard.css' %}">
{% endblock css %}
{% block main-content %}
<div class="content">
    <div class="row content-main">
        <div class="title">
            <h4>Menu</h4>
        </div>
        <div class="form">
            <form action="{% url 'game:start' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="bet_point">Bet Points</label>
                    <input type="number" name="choice_bet_point" id="choice_bet_point" value="25" class="form-control">
                    <p id="message" class="message">{{error}}</p>
                </div>
                <button type="submit" id="start" class="btn btn-success">Start</button>
                <a href="{% url 'wallet:buy_point' %}" id="top_up" class="btn btn-success">Top up here</a>
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}
{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        $('#top_up').hide()
        var messageElement = document.getElementById('message');
        var profilePoint = {{ profile.point }};
        if (profilePoint === 0) {
            messageElement.textContent = 'Please top up to continue.';
            messageElement.style.color = 'black';
            $('#start').hide()
            $('#top_up').show()
        }
    });
</script>
{% endblock js %}